version: "3"
services:
  mockoon:
    image: mockoon/cli:latest
    command: -d /data # this is where the change takes place
    container_name: myapi
    ports:
      - "8888:3000"
    networks:
      demo:
    volumes:
      - type: bind
        source: ../../api/Scheduler_Updated_Latest_OpenAPI_Spec.json    
        target: /data 

networks:
  demo:
    driver: bridge 
